export const USER_CHANGE = 'USER_CHANGE';

export const INIT_GET_CURRENT_USER_INFO = 'INIT_GET_CURRENT_USER_INFO';
export const SET_CURRENT_USER_INFO = 'SET_CURRENT_USER_INFO';

export const INIT_SET_FORUMS = 'INIT_SET_FORUMS';
export const SET_FORUMS = 'SET_FORUMS';
